#config.yml

project_name: my_project

#----- param for dir -----------
#make sure path ends with /
#project_parent_dir: './project/'
project_parent_dir: './project/'

#uncomment if you like to override
#we we create folder for project_name under this dir (if missing)
#project_dir: './project/my_project/'
#we will store images in data sub-folder (./project/my_project/data)
#project_data_dir: './project/my_project/data/'

#temp_dir: './temp/'
#will be used to store non classified images
temp_dir: './temp/'


#----- param for image capture -----------
#src_video: 0 #for primary web cam
#src_video: 'rtsp://username:password@192.168.1.10:554/stream1' #remote ip cam
src_video: 0
file_ext: '*.jpg'
reduce_image_wh_by: 3

#crop % from left or right of image
crop_image_from_left: 0.0 #eg: 0.20 <- crop 20% on left
crop_image_from_right: 0.0 #eg: 0.70 <- crop 30% on right

#----- param for labels -----------
labels_from_dir: False
#labels to use if labels_from_dir was False
labels:
    drinking
    siting
    standing

#--- Param to be used to build and test model --
model_file: './my_project_model.h5'
input_img_height: 224
input_img_width: 224

train_augumentation:
    contrast_range: [-1.0, 1.0]
    brightness_delta: [-50, 50]
    random_rotation: [-0.03, 0.03]
    random_zoom: [-0.05, 0] #-ve is zoom in
    #random_flip: horizontal_and_vertical or horizontal or vertical or none
    random_flip: 'none'

#1 - base cnn
#2 - transfer learning cnn
model_to_try: 2

# For 1
#model_base: ''
# For 2
#model_base: ResNet50, ResNet50V2, 
model_base: 'ResNet50V2'

train_freeze_base_layer: False
train_freeze_skip_last_layers: 90
